### ISSUE TITLE
Connect to regtest Node

### ISSUE THREAD

**Issue by PeterRogers123** [CodeByZ/bitcoin-json-rpc-proxy#1]
Hi there 

Is it at all possible to connect this to the Regtest node for bitcoin core?

Please let me know urgently.

Thanks

**Comment by zackypick** [comment]
Hi Peter,
I see no reason why it wouldn’t work.
Regards

**Comment by PeterRogers123** [comment]
Hi Zacky 

So i currently have both of these installed the json-rpc-proxy and the blockhain explorer.
I am doing this on centos and i can connect to the blockchain explorer just fine.
My Problem is that when i try to login to the blockchain explorer using my server IP and port it wont accept my RPC username and password.

Im not sure if i have not configured correctly or maybe im missing something.

Kind Regards

**Comment by zackypick** [comment]
You probably misconfigured something. What’s the error you are getting?

**Comment by PeterRogers123** [comment]
i am getting no error returned it just doesn't
 authenticate

**Comment by zackypick** [comment]
Surely there is an error. Check the browser devtools console log, or the proxy’s log

**Comment by PeterRogers123** [comment]
The only error i can see in the console is 
Source map error: request failed with status 404
Resource URL: http://localhost:2510/welcome
Source Map URL: bootstrap.css.map[Learn More]

In the debug console i only see that all the request we are sending are unauthenticated.

**Comment by PeterRogers123** [comment]
See below;

--request
POST //connect HTTP/1.1
Host: 192.168.172.167:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost:2510/welcome
Content-Type: application/json
Content-Length: 76
Origin: http://localhost:2510
Connection: keep-alive

--response
HTTP/1.1 401 Unauthorized
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 34
ETag: W/"22-r9qmJzdrfA0Z6o3nqZQHoh5o544"
Date: Wed, 17 Apr 2019 12:22:15 GMT
Connection: keep-alive

**Comment by zackypick** [comment]
Seems your bitcoin core node’s rpc user/pass are not configured properly. Follow the instructions, check Bitcoin.conf settings and that your settings are indeed loaded / in effect.

**Comment by PeterRogers123** [comment]
Bitcoin core settings are correct as i can connect to my bitcoin core API successfully.
This is why i susspect that bitcoin core running in regtest mode is causing the issue.
See Settings below:
regtest = 1
server=1
disablewallet=1
rpcuser=rpc1
rpcpassword=rpcpass
txindex=1
rpcallowip=127.0.0.1

**Comment by zackypick** [comment]
Are you running the node with the -regtest flag? If so it might be that the rpc server is exposed on port 18332 instead of the standard 8332. See the below link. In that case just update the port number in the REST connect proxy request params

https://bitcoin.stackexchange.com/questions/39073/how-to-use-bitcoind-jsonrpc-for-regtest-or-testnet-server-in-php

**Comment by PeterRogers123** [comment]
![image](https://user-images.githubusercontent.com/48350204/56292909-60ac4700-6128-11e9-8ce3-02f901c9c121.png)

my Json RPC is accessible via the port im trying to use as show above but the Blockchain explorer doesnt want to connect to the node

**Comment by zackypick** [comment]
Did you try setting rpcallowip=0.0.0.0/0 in your bitcoin.conf file?

**Comment by PeterRogers123** [comment]
i did try that and that makes it accessible from all computers on my network but the client still fails.
Just on a side note i am building this from source

**Comment by zackypick** [comment]
I think first you need to establish the fact you can actually connect to the rpc server with these credentials without the proxy sitting in the middle, e.g. using curl: 

`curl --user _username_:_passwd_--data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getinfo","params":[]}' -H 'content-type:text/plain;' http://_node_ip_:18332`

**Comment by PeterRogers123** [comment]
I have already communicated and posted many transaction to the Regtest node using a c# project that is successful.

**Comment by PeterRogers123** [comment]
See below the error that returns in my web console when trying to login
Source map error: request failed with status 404 Resource 
URL: http://localhost:2510/scripts.bundle.js 
Source Map URL: bootstrap.js.map[Learn More]

**Comment by PeterRogers123** [comment]
See log.
I changed my network to testnet and i have fully downloaded the node and can communicate to the Port server and RPC just fine except from within the client.

See log below:
192.168.172.167:8080//connect:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by PeterRogers123** [comment]
Ok so i decided to totally remove the project and now re downloaded both projects.
Blochain-explorer does not work on centos as it doesnt build:
src/app/app.module.ts(31,31): error TS2307: Cannot find module 'ngx-clipboard/dist'

**Comment by PeterRogers123** [comment]
I have resolved this issue,

**Comment by zackypick** [comment]
Happy to hear!
